//subsequences(a subsequences of a string is the one which is generated by deleting 0 or more 
// letters from the string and keeping the rest of the letters in the same )

#include<iostream>
#include<vector>
using namespace std;

void solve( string str, string output, int index, vector<string> &ans){
    if(index >= str.length()){   //base case 
        ans.push_back(output);
        return; 
    }

    solve(str, output, index+1, ans );  // exclude

    char element = str[index];
    output.push_back(element);
    solve (str, output, index+1, ans );   // include
}


vector<string> subsequences(string str){
    vector<string> ans;
    string output = " ";
    int index = 0;

    solve(str, output, index, ans);
    return ans;
}

int main(){

    vector<string> v = "mahesh";
    subsequences(v);

    return 0;
}